mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: admin123
  log_level: dev
logger: 
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: 2024-06-55
  bei_an: 皖ICP备2021010654号-1
  title: 阿猛的blog
  qq_image: http://www.fengfengzhidao.con/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2663456523@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 阿猛blog
  job: 后瑞开发
  addr: 广东深圳
  sLogan: 美玲博容 HEILINGBLOG
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://qithub.com/fengfengzhidao/
upload:
  size: 2
  path: uploads/file
qq:
  app_id: '102103791'
  key: 'GLCtgGbibFfqovoS'
  redirect: http://blog.amengzhidao.com/login?flag=qq
qi_niu:
  enable: true
  access_key: 'yw_M88datflralONkuBOAVX3tht9IechncvaPUth'
  secret_key: 'uF1xzJZHA4Iki79jwtH6E92m8LRThIMrYOxnkvIq'
  bucket: mengmengzhidao
  cdn: http://sbxobim36.hn-bkt.clouddn.com/
  zone: z2
  prefix: "gvb"
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: '1316937247@qq.com'
  password: 'dagczyvdjrrogdje'
  default_from_email: 阿猛知道
  use_ssl: false
  user_tls: false
jwt:
  secret: '******'
  expires: 20
  issuer: "1234"
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  isAnonymous: true
  isShowTime: false
  defaultLimit: 50
  contentLength: 101
  welcomeTitle: 枫枫知道在线聊天室
  isOnlinePeople: true
  isSendImage: true
  isSendFile: false
  isMd: true
gaode:
  enable: true
  key: '******'
